### ISSUE TITLE
[BUG] `2x [ADDON_ACTION_BLOCKED] AddOn 'EnhancedRaidFrames' tried to call the protected function 'IsItemInRange()'.`

### ISSUE THREAD

**Issue by tflo** [brittyazel/EnhancedRaidFrames#115]
`IsItemInRange` is a restricted function as of Nov 16.
 
See: [https://www.wowhead.com/blue-tracker/news/eu/hotfixes-november-16-2023-24030413](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowhead.com%252fblue-tracker%252fnews%252feu%252fhotfixes-november-16-2023-24030413)

**Comment by tflo** [comment]
Just seen that the error was triggered by a call of a different addon to the `LibRangeCheck` library inside your`Libs` folder.

I leave it open though, because you are probably also using the function from the lib.

**Comment by brittyazel** [comment]
Actually, funny enough, I'm not using that function. The only function I use out of that library is the UnitAura function, which afaik doesn't have a combat restriction. It's a bummer that these errors get attributed back to me though, probably because our addon name loads first alphabetically, so it's our included libs that get loaded first :-/

**Comment by tflo** [comment]
OK, sorry for the noise in the wrong place then ;)

Yes, AFAIK, it's always the first lib instance that gets used; stupid system. Rename your addon to "ZuperEnhancedRaidFrames" 🙃

**Comment by brittyazel** [comment]
Not a problem, I would rather get the issue reports than not ;-)
