### ISSUE TITLE
Timer text appearing behind Stock Buff/Debuff Icons?

### ISSUE THREAD

**Issue by eightflat** [brittyazel/EnhancedRaidFrames#72]
## Issue description:
Hello! I'm not absolutely certain that this was not always the case, but it seems the most recent update has done something to make the timer text appear behind the countdown swipe of the _Stock Buff/Debuff_ icons. Thank you for all your work!

## How to reproduce:
**1.** Have _Countdown_ text enabled for any aura.
**2.** Have _Stock Buff Icons_ and _Stock Debuff Icons_ enabled.
**3.** Observe that the timer text appears to be occluded by the shadowed portion of the countdown swipe of the _Stock Buff/Debuff Icons_.

## Technical info:
ERF 3.3.4
Retail 9.0.2

## Screenshots:
**Examples**: https://imgur.com/a/egJykKf, https://imgur.com/a/3Xlf6gN

## Lua error log:
No LUA errors.

**Comment by brittyazel** [comment]
Hrm I've very confused what is happening in this shot.

So you are using the stock buff and debuff frames, and the issue is that the stock aura icons have the text layered behind the swipe animation?

If so, ERF doesn't touch the stock buff/debuff frames at all except to either hide them, depending on user preference. I have absolutely zero idea why anything that changed in the last day or so would have influenced these stock aura frames as we literally do nothing to them.

When ERF is disabled, do the stock frames have the countdown text on top or behind of the swipe animation? It may be that this was the intended Blizzard behavior :-/

**Comment by brittyazel** [comment]
Got it, new release coming asap

**Comment by eightflat** [comment]
You are the best, worked like a charm! https://imgur.com/a/DTS023k

**Comment by brittyazel** [comment]
Awesome thanks for reporting this bug :-)
